### ISSUE TITLE
Gigperformer4 stalls when loading a 'gig' with ysfx

### ISSUE THREAD

**Issue by frank1119** [jpcima/ysfx#55]
In Gigperformer a project is called a gig. When I load a gig with ysfx included as a plugin Gigperformer is stuck telling me it is trying to load ysfx. Loading a gig without ysxf and then adding it works normal. (But then, I want to save the gig, that succeeds, but loading does fail).

It does not matter whether ysxf has a script loaded or not.

This is on Windows 11, no cpu load from Gigperformer. Maybe some event, semaphore or deadlock?

FYI: Reaper exhibits the same behavior

**Comment by jpcima** [comment]
This problem is occurring while initially loading plugin state.
In short:
- the background thread is picking up the load-file request
- background thread compiles and loads JSFX
- calls juce's MessageManager to synchronously suspend the DSP and install the JSFX

It hangs here, because GP apparently is not processing the messages at this point, and the plugin is forever waiting a result which doesn't arrive.

Blocking happens precisely here
https://github.com/jpcima/ysfx/blob/b34649e85e23be82223ae953498cce99e221a999/plugin/processor.cpp#L600

**Comment by frank1119** [comment]
Thanks for the explanation. It seems a bit wider problem than just Gigperformer: Reaper has the same issues. 

**Just for my information**: Is this something someone is going to fix? I do not mean any pressure. For now I use the Jan 12th 2022 version, so I’m fine (I’m fine anyway, but that aside 😀)

Thanks.

**Comment by jpcima** [comment]
This is hopefully fixed in the revision b1921b6.

**Comment by frank1119** [comment]
I checked. It now loads and works. Thank you very much.
